backend_ws_get_infos_add_game:
    pattern:  /ws/infos/infos_create_game
    defaults: { _controller: BackendWsBundle:Infos:createGame }
    
backend_ws_delete_game_catalog:
    pattern: /ws/game_catalog/{id}/delete
    defaults: { _controller: BackendWsBundle:GameCatalog:deleteGameCatalog }