parameters:
#    backend_ws.example.class: Backend\WsBundle\Example

services:
#    backend_ws.example:
#        class: %backend_ws.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
