imports:
    - { resource: config.yml }

framework:
    secret: %secret%
    translator:      { fallback: %prod_locale% }
    default_locale:  "%prod_locale%"
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc
    
swiftmailer:
    transport: %prod_mailer_transport%
    host:      %prod_mailer_host%
    username:  %prod_mailer_user%
    password:  %prod_mailer_password%
    
monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %prod_driver%
        host:     %prod_host%
        port:     %prod_port%
        dbname:   %prod_dbname%
        user:     %prod_user%
        password: %prod_password%
        charset:  %prod_charset%

parameters:
   super_admin_email: %prod_super_admin_email% 
   
fos_user:
    from_email:
        address:        %prod_mailer_user%
        sender_name:    Rompy