imports:
    - { resource: config_dev.yml }

framework:
    secret: %secret%
    translator:      { fallback: %locale% }
    default_locale:  "%locale%"
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    disable_delivery: true

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %driver%
        host:     %host%
        port:     %port%
        dbname:   %dbname%
        user:     %user%
        password: %password%
        charset:  %charset%

fos_user:
    from_email:
        address:        %mailer_user%
        sender_name:    Rompy