imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:      
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    trusted_proxies: ~
    session:
        cookie_lifetime:   10800
    fragments: { path: /_fragment }

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        current_revision: %current_revision%
        contact_mail: %contact_mail%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [FrontendFrontOfficeBundle, FrontendBackOfficeBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        dql:
            string_functions:
                MONTH: DoctrineExtensions\Query\Mysql\Month
                YEAR: DoctrineExtensions\Query\Mysql\Year

# Swiftmailer Configuration
swiftmailer:
    encryption: tls
    # auth_mode: login
    # spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: frontend
    user_class: Frontend\FrontOfficeBundle\Entity\User
    registration:
      form:
        type: frontend_user_registration
        validation_groups: [Register]
    resetting:
      form:
        type: carpaccio_user_reset
        validation_groups: [Reset]
    change_password:
      form:
        type: carpaccio_user_change_password
    profile:
        form:
            type: frontend_user_profile_update
   