imports:
    - { resource: config.yml }

framework:
    secret: %secret%
    translator:      { fallback: %locale% } 
    default_locale:  "%locale%"
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false
    
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    port:      %mailer_port%
monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info

assetic:
    use_controller: true

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %driver%
        host:     %host%
        port:     %port%
        dbname:   %dbname%
        user:     %user%
        password: %password%
        charset:  %charset%

parameters:
   super_admin_email: %super_admin_email% 
   
fos_user:
    from_email:
        address:        %mailer_user%
        sender_name:    Rompy
