security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:   ROLE_USER
        ROLE_SUPERADMIN:   [ROLE_USER, ROLE_ADMIN]

    providers:
        frontend:
          entity: { class: Frontend\FrontOfficeBundle\Entity\User, property: username }
        #fos_userbundle:
            #id: fos_user.user_provider.username_email
            #users:
            #  user:     { password: userpass, roles: [ 'ROLE_USER' ] }
            #  manager:  { password: managerpass, roles: [ 'ROLE_MANAGER' ] }
            #  admin:    { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        #backend:
        #    pattern:  ^/backend
        #    anonymous:  false

        frontend:
            pattern:  /
            # form_login:
            #  provider: fos_userbundle
            #  csrf_provider: form.csrf_provider
            form_login:
                login_path: frontend_frontoffice_homepage
                check_path: fos_user_security_check
                default_target_path:  frontend_frontoffice_homepage
                target_path_parameter:  _target_path
            logout:
              path: fos_user_security_logout
              target: frontend_frontoffice_homepage
            remember_me:
              key: %secret%
              lifetime: 21600
              path:     /
              domain:   ~
            anonymous: true

    access_control:
        #^/(en|fr)
        - { path: ^/(en|fr)/profile/*, role: ROLE_USER }
        - { path: ^/(en|fr)/seller/[0-9]*/game/[0-9]*/contact, role: ROLE_USER }
        - { path: ^/(en|fr)/*, role: IS_AUTHENTICATED_ANONYMOUSLY }
