frontend_frontoffice_homepage:
    pattern:  /{_locale}
    defaults: { _controller: FrontendFrontOfficeBundle:Home:index, _locale: fr }
    requirements:
          _locale: fr
   
frontend_frontoffice_homepage_slash:
    pattern:  /{_locale}/
    defaults: { _controller: FrontendFrontOfficeBundle:Home:index, _locale: fr }
    requirements:
          _locale: fr
          
frontend_frontoffice_profile_home:
    pattern:  /{_locale}/profile
    defaults: { _controller: FrontendFrontOfficeBundle:Profile:index, _locale: fr }
    requirements:
          _locale: fr
          
frontend_frontoffice_profile_home_slash:
    pattern:  /{_locale}/profile/
    defaults: { _controller: FrontendFrontOfficeBundle:Profile:index, _locale: fr }
    requirements:
          _locale: fr
          
frontend_frontoffice_profile_add_game:
    pattern:  /{_locale}/profile/add_game
    defaults: { _controller: FrontendFrontOfficeBundle:Profile:addGame, _locale: fr }
    requirements:
          _locale: fr

frontend_frontoffice_profile_update:
    pattern:  /{_locale}/profile/update
    defaults: { _controller: FrontendFrontOfficeBundle:Profile:update, _locale: fr }
    requirements:
          _locale: fr
          
frontend_frontoffice_common_get_all_games:
    pattern:  /ws/all_games
    defaults: { _controller: FrontendFrontOfficeBundle:Common:getAllGames}
    
frontend_frontoffice_common_get_game_info:
    pattern:  /ws/game/info
    defaults: { _controller: FrontendFrontOfficeBundle:Common:getGameInfo}
    
frontend_frontoffice_common_get_game_catalog_info:
    pattern:  /ws/catalog/game/info
    defaults: { _controller: FrontendFrontOfficeBundle:Common:getGameCatalogInfo}
    
frontend_frontoffice_common_get_last_add_games:
    pattern:  /ws/last_adds
    defaults: { _controller: FrontendFrontOfficeBundle:Common:getLastAddGames}