<?php

namespace Frontend\FrontOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EditorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EditorRepository extends EntityRepository
{
    public function array_findAll()
    {
        $allEditors = $this->findAll();
        
        $editors = array();
        foreach($allEditors as $k=>$e)
        {
            $editors[$k]["id"] = $e->getId();
            $editors[$k]["value"] = $e->getValue();
        }
        
        return $editors;
    }
}
