<?php

namespace Frontend\FrontOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GameTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameTypeRepository extends EntityRepository
{
    public function findAllOrdered() {
        $qb = $this->createQueryBuilder("gt");
            
        $query = $qb->select('gt.id, gt.value')
         ->orderby('gt.value', 'ASC')
         ->getQuery();
         
        return $query->getResult();
    }
}
