<?php

namespace Frontend\FrontOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GameTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameTypeRepository extends EntityRepository
{
    public function array_findAll()
    {
        $allGameTypes = $this->findAll();
        
        $gameTypes = array();
        foreach($allGameTypes as $k=>$gt)
        {
            $gameTypes[$k]["id"] = $gt->getId();
            $gameTypes[$k]["value"] = $gt->getValue();
        }
        
        return $gameTypes;
    }
}
