<?php

namespace Frontend\FrontOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GameStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameStateRepository extends EntityRepository
{
    public function array_findAll()
    {
        $allGameStates = $this->findAll();
        
        $gameStates = array();
        foreach($allGameStates as $k=>$gs)
        {
            $gameStates[$k]["id"] = $gs->getId();
            $gameStates[$k]["value"] = $gs->getValue();
        }
        
        return $gameStates;
    }
}
