<?php

namespace Frontend\FrontOfficeBundle\Entity;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDisplayedNews(\Datetime $now)
    {
        $qb = $this->createQueryBuilder('n');
        
        $data = $qb->where($qb->expr()->between(':date_now', 'n.dateStart', 'n.dateEnd'))
                    ->setParameter('date_now', $now, \Doctrine\DBAL\Types\Type::DATETIME)
                    ->orderBy("n.dateStart", "desc")
                    ->getQuery()
                    ->getResult();
        
        return $data;
    }
}
