<?php

namespace Frontend\FrontOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlateformRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlateformRepository extends EntityRepository
{
    public function array_findAll()
    {
        $allPlateforms = $this->findAll();
        
        $plateforms = array();
        foreach($allPlateforms as $k=>$p)
        {
            $plateforms[$k]["id"] = $p->getId();
            $plateforms[$k]["value"] = $p->getValue();
        }
        
        return $plateforms;
    }
}
