<?php

namespace Frontend\FrontOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlateformRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlateformRepository extends EntityRepository
{
    public function findAllOrdered() {
        $qb = $this->createQueryBuilder("p");
            
        $query = $qb->select('p.id, p.value')
         ->orderby('p.value', 'ASC')
         ->getQuery();
         
        return $query->getResult();
    }
}
