<?php

namespace Frontend\FrontOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SellerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SellerRepository extends EntityRepository
{
    public function getSellerInfos($id)
    {
        $qb = $this->createQueryBuilder("se");
	    
	    $query = $qb->select('u.id as user_id, u.username, u.email')
        ->leftJoin('se.user', 'u')
        ->where('u.id='.$id)
        ->getQuery();
        
        $infos = $query->getResult();
        
        return $infos;
    }
}
