<?php

namespace Frontend\FrontOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SeriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeriesRepository extends EntityRepository
{
    public function array_findAll()
    {
        $allSeries = $this->findAll();
        
        $series = array();
        foreach($allSeries as $k=>$s)
        {
            $series[$k]["id"] = $s->getId();
            $series[$k]["value"] = $s->getValue();
        }
        
        return $series;
    }
}
