<?php

namespace Frontend\FrontOfficeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {
    public function findTodayRegistration() {
        $d1 = new \DateTime();
        $d1->setTime(0, 0, 0);
        
        $qb = $this->createQueryBuilder("u");

        $query = $qb->select("u.id")
                ->where("u.registered_at >= :date")
                ->setParameter('date', $d1)
                ->getQuery();

        $lastRegistrations = $query->getResult();

        return $lastRegistrations;
    }
}
