frontend_back_office_homepage:
    pattern:  /
    defaults: { _controller: FrontendBackOfficeBundle:Home:index }

frontend_back_office_games:
    pattern:  /games
    defaults: { _controller: FrontendBackOfficeBundle:Game:index }
    
frontend_back_office_users:
    pattern:  /users
    defaults: { _controller: FrontendBackOfficeBundle:User:index }
    
frontend_back_office_news:
    pattern:  /news
    defaults: { _controller: FrontendBackOfficeBundle:News:index }    
    
frontend_back_office_gametypes:
    pattern:  /game-types
    defaults: { _controller: FrontendBackOfficeBundle:Gametype:index }
    
frontend_back_office_plateformes:
    pattern:  /plateforms
    defaults: { _controller: FrontendBackOfficeBundle:Plateforme:index }
    
frontend_back_office_profile_update_plateform:
    pattern: /plateforms/update/{id}/{name}/{hash}
    defaults: { _controller: FrontendBackOfficeBundle:Plateforme:update }
    
frontend_back_office_profile_create_plateform:
    pattern: /plateforms/create
    defaults: { _controller: FrontendBackOfficeBundle:Plateforme:create }
    
frontend_back_office_profile_delete_plateform:
    pattern: /plateforms/delete/{id}/{name}/{hash}
    defaults: { _controller: FrontendBackOfficeBundle:Plateforme:delete }