frontend_back_office_homepage:
    pattern:  /
    defaults: { _controller: FrontendBackOfficeBundle:Home:index }

frontend_back_office_games:
    pattern:  /games
    defaults: { _controller: FrontendBackOfficeBundle:Game:index }
    
frontend_back_office_users:
    pattern:  /users
    defaults: { _controller: FrontendBackOfficeBundle:User:index }
    
frontend_back_office_news:
    pattern:  /news
    defaults: { _controller: FrontendBackOfficeBundle:News:index }    
    
frontend_back_office_gametypes:
    pattern:  /game-types
    defaults: { _controller: FrontendBackOfficeBundle:Gametype:index }
    
frontend_back_office_plateformes:
    pattern:  /plateforms
    defaults: { _controller: FrontendBackOfficeBundle:Plateforme:index }