parameters:
#    frontend_back_office.example.class: Frontend\BackOfficeBundle\Example

services:
#    frontend_back_office.example:
#        class: %frontend_back_office.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
